config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :coaches
  resources :exercises 
 
  root 'exercises#index'
  get "bootstrap", to: "exercises#bootstrap"
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
    has_and_belongs_to_many :exercises
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :coach
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :exercises
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController

  # Show all coaches
def index
 @coaches = Coach.all  
end

  # To view one coach
def show 
  @coach = Coach.find(params[:id])
end 

# To create a new coach
def new
  @coach = Coach.new
end

def edit
  @coach = Coach.find(params[:id])
end
# To create a new coach
def create
@coach = Coach.new(coach_params)

@coach.save

redirect_to @coach

end

# To Update Coach
def update
  @coach = Coach.find(params[:id])

  @coach.update(coach_params)

  redirect_to  @coach
  
  end
# To Delete Coach
def destroy
  @coach = Coach.find(params[:id]).delete

  redirect_to coaches_path
end

private

def coach_params
  params.require(:coach).permit(:name, :specialty)
end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :index, :destroy, :update, :edit]

  before_action :find_exercise, only: [:show, :edit, :update, :destroy]

  # Show all exercises
    def index
    @exercises = current_user.exercises.all  
      
    end
    # To view one exercises
    def show
    if @exercise.user != current_user
    flash[:notice] = "Not Allowed!"
    redirect_to exercises_path
    end
    end
    # To create a new exercise
    def new
    @exercise = Exercise.new
      end
    # To edit a exercise
    def edit
    @exercise = Exercise.find(params[:id])
    end

    # To create a new exercise
    def create
    @exercise = Exercise.new(exercise_params)
    @exercise.user = current_user 
       
    if @exercise.save
    redirect_to @exercise
    else 
    puts "else"
    render :new
    end 

    end

   # To update a exercise

    def update
    @exercise = Exercise.find(params[:id])
    @exercise.update(exercise_params)
    redirect_to  @exercise
        
    end
  # To Delete a exercise
    def destroy
    @exercise = Exercise.find(params[:id]).delete
    redirect_to exercises_path
     end
   
   private
   def exercise_params
   params.require(:exercise).permit(:name, :explain, :img, :coach_id)
   end
       
   # To find exercise a exercise
    def find_exercise
    @exercise = Exercise.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coach_helper.rb
module CoachHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/coach/show.html.erb
<h2> Coach </h1>
<div>
<%= @coach.name %>
</div>
<%= @coach.specialty %>
</div>
</div>

app/views/coaches/_form.html.erb
<div class="container justify-content-lg-center">
<%=form_for @coach do |form| %>
   <div class="form-group">
   <label for="exampleFormControlInput1"> Coach Name </label>
   <input type="text" class="form-control" <%=form.text_field :name %>
    </div>
    <div  class="form-group">
    <label for="exampleFormControlInput1"> Coach Specialty</label>
    <input type="text" class="form-control" <%=form.text_field :specialty %>
    </div>
    <button class="btn btn-light"><%= form.submit %> </button>
    <% end %>
    </div>

app/views/coaches/edit.html.erb
<%= render partial: 'form', locals: { coaches: @coaches} %>

app/views/coaches/index.html.erb
<div class="container justify-content-lg-center">
<nav>
        <ul class="nav nav-tabs">
          <li class="nav-item">   <a class="nav-link active" <%= link_to 'Exercise', exercises_path %></li></a>
          <li class="nav-item"><a class="nav-link active" <%= link_to 'Coach', coaches_path %></li></a>
          <% if user_signed_in? %>
            <li class="nav-item"> <a class="nav-link active" <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li></a>
          <% end %>
          <li class="nav-item"><a class="nav-link active" <%= link_to "Add an Coach", new_coach_path %></li></a>
        </ul>
      </nav>
<table  class="table table-striped">
  <tr>
    <th scope="col">Coach Name</th>
    <th scope="col">Coach Specialty</th>
    <th scope="col">Edit</th>
    <th scope="col">Delete</th>
  </tr>
  <% @coaches.each do |coach| %>
      <tr>
        <td><%= link_to coach.name, coach_path(coach) %></td>
        <td><%= coach.specialty %></td>
      
        <td><button type="button" class="btn btn-light"><a href="<%= edit_coach_path(coach) %>" > Edit
          </a>
          </button>
          </td>
          <td> <button type="button" class="btn btn-light"><%=link_to 'Delete' ,coach_path(coach.id) ,method: :delete, data: { confirm: 'Are you sure?' }%> 
          </button></td>
      </tr>
  <% end %>
</table>
</div>

app/views/coaches/new.html.erb
<%= render partial: 'form', locals: { coaches: @coaches} %>

app/views/coaches/show.html.erb
<div class="container justify-content-center " >
<div class="card border-primary mb-3 ">
<div class="card-header"> Coach </div>
<div class="card-text">
<%= @coach.name %>
</div>
<div class="card-header">
<%= @coach.specialty%>
</div>
</div>
</div>

app/views/exercises/_form.html.erb
<div class="container justify-content-lg-center">
<%=form_with model:@exercise, local: true do |form| %>
    <div class="form-group">
    <label for="exampleFormControlInput1">Exercise Name </label>
    <input type="text" class="form-control"<%=form.text_field :name %> 
    </div>
    <div class="form-group">
    <label for="exampleFormControlInput1">Exercise Explain </label>
    <input type="text" class="form-control" <%=form.text_area :explain %>
    </div>
    <div class="form-group">
    <label for="exampleFormControlInput1">Exercise Img </label>
    <input type="text" class="form-control"<%=form.text_field :img %>
    </div>
    <div class="form-group">
    <label for="exampleFormControlSelect1"> <%= form.label :coach %> </label><br>
    <select class="form-control" 
    <%= form.collection_select :coach_id, Coach.all, :id, :name, { include_blank: 'None' }%></select>
  </div>
    <button type="button" class="btn btn-light"><%= form.submit %></button>
    <% end %>
 </div>

app/views/exercises/edit.html.erb
<%= render partial: 'form', locals: { exercise: @exercise} %>

app/views/exercises/index.html.erb
<body>
<div class="container justify-content-lg-center">
<header>
<p>
  Welcome <%= current_user.email %>
</p>
</header>
<nav >
        <ul class="nav nav-tabs">
          <li class="nav-item">   <a class="nav-link active" <%= link_to 'Exercise', exercises_path %></li></a>
          <li class="nav-item"><a class="nav-link active" <%= link_to 'Coach', coaches_path %></li></a>
          <% if user_signed_in? %>
            <li class="nav-item"> <a class="nav-link active" <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li></a>
          <% end %>
          <li class="nav-item"><a class="nav-link active" <%= link_to "Add an Exercise", new_exercise_path %></li></a>
        </ul>
      </nav>
    
<table class="table table-striped">
  <tr>
    <th scope="col">Exercise</th>
    <th scope="col">Image</th>
    <th scope="col">Explain</th>
    <th scope="col">Edit</th>
    <th scope="col">Delete</th>
  </tr>
  
  <% @exercises.each do |exercise| %>
      <tr >
        <td ><%= link_to exercise.name, exercise_path(exercise) %></td>
        <td><%= image_tag(exercise.img, size: "200x200", alt: "exercise Image") %></td>
        <td ><%= exercise.explain %></td>
        
        <td><button type="button" class="btn btn-light"><a href="<%= edit_exercise_path(exercise) %>" > Edit
          </a>
          </button>
        </td>
        <td><button type="button" class="btn btn-light"> <%=link_to 'Delete' ,exercise_path(exercise.id) ,method: :delete, data: { confirm: 'Are you sure?' }%> </button>
          </td>
         
      </tr>
  <% end %>
</table>
</div>

</body>

app/views/exercises/new.html.erb
<%= render partial: 'form', locals: { exercise: @exercise} %>

app/views/exercises/show.html.erb
<div class="container justify-content-lg-center">
<div class="card border-primary mb-3" >
<div class="card-header">

<%= @exercise.name %>
</div>
<div class="card-text">

<%= image_tag(@exercise.img, size: "255x255", alt: "exercise Image") %>
</div>
<div class="card-text">

<%= @exercise.explain %>
</div>
<div  class="card-header">

<%= Coach.find(@exercise.coach_id).name %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>

   
  </body>
</html>